// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB56tmLqIODe5EFX3lgpP-caGvuvet9pw8',
    appId: '1:550354877281:web:8347828174ab6c9d122320',
    messagingSenderId: '550354877281',
    projectId: 'myapp-firebase-66249',
    authDomain: 'myapp-firebase-66249.firebaseapp.com',
    storageBucket: 'myapp-firebase-66249.appspot.com',
    measurementId: 'G-CJSK7LV58L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3sF7IiR9uE1yvldRVK5_hlGlw3oyx5a0',
    appId: '1:550354877281:android:11a98bb9af0cc4e9122320',
    messagingSenderId: '550354877281',
    projectId: 'myapp-firebase-66249',
    storageBucket: 'myapp-firebase-66249.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6HcYUa5rjTiqcJvJVM_nm_EcncYkPhLI',
    appId: '1:550354877281:ios:9ce6739cbfa0bdca122320',
    messagingSenderId: '550354877281',
    projectId: 'myapp-firebase-66249',
    storageBucket: 'myapp-firebase-66249.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6HcYUa5rjTiqcJvJVM_nm_EcncYkPhLI',
    appId: '1:550354877281:ios:9ce6739cbfa0bdca122320',
    messagingSenderId: '550354877281',
    projectId: 'myapp-firebase-66249',
    storageBucket: 'myapp-firebase-66249.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB56tmLqIODe5EFX3lgpP-caGvuvet9pw8',
    appId: '1:550354877281:web:565a7db68f16b760122320',
    messagingSenderId: '550354877281',
    projectId: 'myapp-firebase-66249',
    authDomain: 'myapp-firebase-66249.firebaseapp.com',
    storageBucket: 'myapp-firebase-66249.appspot.com',
    measurementId: 'G-0ZDGQP5TNH',
  );
}
